export const MAP_INIT_MAP = 'MAP_INIT_MAP'
export const MAP_SET_ALL_VISIBLE = 'MAP_SET_ALL_VISIBLE'
export const MAP_SET_INVISIBLE = 'MAP_SET_INVISIBLE'


export const EXPORT_SET_VISIBLE = 'EXPORT_SET_VISIBLE'
export const EXPORT_SET_INVISIBLE = 'EXPORT_SET_INVISIBLE'
export const EXPORT_ADD_OBJECT = 'EXPORT_ADD_OBJECT'
export const EXPORT_RESET = 'EXPORT_RESET'
export const EXPORT_REMOVE_OBJECT = 'EXPORT_REMOVE_OBJECT'





